version: '1.0.{build}'

image: Visual Studio 2017

install:
    - git submodule update --init --recursive

before_build:
    - cmake -DBUILD_TESTS=True .

build:
    project: $(APPVEYOR_BUILD_FOLDER)\knn-cpp.sln

test_script:
    - '%APPVEYOR_BUILD_FOLDER%\test\Debug\run_tests.exe'
